<h3 align="left"> Institut für Datenanalyse und Prozessdesign $\qquad \qquad \qquad \qquad \qquad \qquad$  Stephan Bütikofer <br>
ZHAW <br> Lineare Algebra II  </h3> 



<h3 align="center">$\Large Serie \quad 1$ <br>
 (Ausgabe: 24.02.2015 / Abgabe: 09.03.2015) </h3> 
 

###Aufgabe 1
Zeigen Sie, dass die Menge

$$ B = \{ p \in P_2 \; | \; p(1) = p(-1)\} $$

ein Unterraum im Vektorraum $P_2$ der quadratischen Funktion ist. Zeigen Sie,

dass $B$
der Kern einer passenden linearen Abbildung $f$ von $P_2$ nach $\mathbb{R}$ ist.

Bestimmen Sie die
Dimension des Kerns $Ker(f)$ und des Bilds $Im(f)$ von $f$.

###Lösung

####Beweis

$f(p) = p(1) - p(-1) = 0  ; \quad P_2 \rightarrow  \mathbb{R} $

Unterraum Bedingungen: Addition und skalar Multiplikation



$f(\lambda p + \mu q) \quad \quad = (\lambda p + \mu q ) \,(1) - (\lambda p + \mu q ) \,(-1)$ 

$\qquad  \qquad \qquad   = \lambda p \,(1) + \mu q \,(1) - \lambda p \,(-1) - \mu q \,(-1)$

$\qquad  \qquad \qquad= \lambda (p \,(1) - p \,(-1)) + \mu (q \,(1) -  \mu q \,(-1))$

$\qquad  \qquad \qquad=  \lambda f(p) +\mu f(q) $

####Dimension

$dim (P_2) = Lin \{ 1,x,x^2 \} = 3$

Dimensionssatz: 
$$ dim(P_2) = dim(Ker(f)) + dim(Im(f))$$
<br>
<br>

Drei Fälle:

$f(x^2) \rightarrow  1 - 1 = 0 \Longrightarrow dim(Im(f)) = 0$
     
$f(x^2 + x ) \rightarrow  1 - 1 + 2,\, 2 \neq 0 \Longrightarrow dim(Im(f)) = 1 $
     
$f(x^2 + x + a ) \rightarrow  1 - 1 + 2 + a - a,\, 2 \neq 0 \Longrightarrow dim(Im(f)) = 1 $



$$ dim(Ker(f)) = dim(P_2) - dim(Im(f)) =  2$$


In [2]:
import numpy as np
A = np.matrix([[2,0,0]])

print("A in Matrix Form:",A) # unser U Matrix
print("Rank von A ist: dim(Im(f))",np.linalg.matrix_rank(A)) # rank unserer Matrix 
print("Dimension P2 ist: dim(P2)",A.shape[1])
print("Ker(f) =",A.shape[1]-np.linalg.matrix_rank(A)) # Dimension des Lösungsraumes


A in Matrix Form: [[2 0 0]]
Rank von A ist: dim(Im(f)) 1
Dimension P2 ist: dim(P2) 3
Ker(f) = 2




###Aufgabe 2
Sei $f$ die lineare Abbildung gegeben durch

$$ f \left( \begin{array}{c} 1 \\ 0 \\ 0 \end{array} \right) = \left( \begin{array}{c} 1 \\ 1 \end{array} \right), \quad f \left( \begin{array}{c} 0 \\ 1 \\ 0 \end{array} \right) = \left( \begin{array}{c} 3 \\ 1 \end{array} \right), \quad f \left( \begin{array}{c} 0 \\ 0 \\ 1 \end{array} \right) = \left( \begin{array}{c} 1 \\ 4 \end{array} \right)$$

Bestimmen Sie die Matrix $A$, die $f$ bezüglich der kanonischen Basis im $\mathbb{R}^3$ bzw. $\mathbb{R}^2$ darstellt.
Wie sieht die Matrix $A$ aus, wenn man im Bildraum $\mathbb{R}^2$ die Basis $\{(1,1)^T , (3,1)^T \}$ gewählt?




###Lösung

$ \underbrace{\mathbb{R}^3}_\text{kanonische Basen} \qquad  \xrightarrow{A}  \qquad   \underbrace{\mathbb{R}^2}_\text{kanonische Basen} $

$$f(x) = A x$$

### a)

$\left( \begin{array}{c} 1 \\ 1 \end{array} \right) = a_{11} \left( \begin{array}{c} 1 \\ 0 \end{array} \right) + a_{21} \left( \begin{array}{c} 0 \\ 1 \end{array} \right) $ 

$\left( \begin{array}{c} 3 \\ 1 \end{array} \right) = a_{12} \left( \begin{array}{c} 1 \\ 0 \end{array} \right) + a_{22} \left( \begin{array}{c} 0 \\ 1 \end{array} \right)$ 

$\left( \begin{array}{c} 1 \\ 4 \end{array} \right) = a_{13} \left( \begin{array}{c} 1 \\ 0 \end{array} \right) + a_{3} \left( \begin{array}{c} 0 \\ 1 \end{array} \right) $ 

somit: 
$$ A =\begin{pmatrix}
1 & 3 & 1 \\
1 & 1 & 4 \\
\end{pmatrix}
$$

### b)

$\left( \begin{array}{c} 1 \\ 1 \end{array} \right) = a_{11}' \left( \begin{array}{c} 1 \\ 1 \end{array} \right) + a_{21}' \left( \begin{array}{c} 3 \\ 1 \end{array} \right) $ 

$\left( \begin{array}{c} 3 \\ 1 \end{array} \right) = a_{12}' \left( \begin{array}{c} 1 \\ 1 \end{array} \right) + a_{22}' \left( \begin{array}{c} 3 \\ 1 \end{array} \right)$

$\left( \begin{array}{c} 1 \\ 4 \end{array} \right) = a_{13}' \left( \begin{array}{c} 1 \\ 1 \end{array} \right) + a_{23}' \left( \begin{array}{c} 3 \\ 1 \end{array} \right) $ 

somit: 

$$A' = \begin{pmatrix}
1 & 0 & 5.5 \\
0 & 1 & -1.5 \\
\end{pmatrix}
$$


In [3]:
a1 = np.matrix([[1,3],[1,1]])
b1 = np.array([1,1])
[a11,a21] = np.linalg.solve(a1, b1)
a2 = np.matrix([[1,3],[1,1]])
b2 = np.array([3,1])
[a12,a22] = np.linalg.solve(a2, b2)
a3 = np.matrix([[1,3],[1,1]])
b3 = np.array([1,4])
[a13,a23] = np.linalg.solve(a3, b3)
A = np.matrix([[a11,a12,a13],[a21,a22,a23]])
A


matrix([[ 1. ,  0. ,  5.5],
        [-0. ,  1. , -1.5]])

###Aufgabe 3

Wir betrachten die (lineare) Ableitungsfunktion $f$ vom Vektorraum der
quadratischen Funktion $P_2$ in den Vektorraum der linearen Funktionen $P_1$, d.h.
$$f(p) = p', \quad f:p(x) = ax^2+bx+c \mapsto p'(x) = 2ax +b$$

(a) Beschreiben Sie $f$ durch eine Matrix $A$ bezüglich den Basen $\{1, x , x^2 \}$ in $P_2$ bzw.
$\{1,x \}$ in $P_1$.

(b) Berechnen Sie mit Hilfe der Matrix $A$ die Ableitung von $x^2 + x$.

###Lösung

####a)

$$ f:P_2 \rightarrow P_1, \quad  p(x) \mapsto f(p) = p' $$
$$f(p_j(x)=\sum_{i=0}^1 a_{ij}x^i = a_{0j}  + a_{1j}x = jx^{j-1}$$

Für $j = 0:$

$a_{00} + a_{10}x = 0 \Longrightarrow  a_{00} = a_{10} = 0$

Für $j = 1:$

$a_{01} + a_{11}x = 1 \Longrightarrow  a_{01} = 1, \quad a_{11} = 0$   

Für $j = 2:$ 

$a_{02} + a_{12}x = 2x \Longrightarrow  a_{02} = 0, \quad a_{12} = 2$

somit:
$$   
A =\begin{pmatrix}
0 & 1 & 0 \\
0 & 0 & 2 \\
\end{pmatrix}
$$ 

####b)

 $x^2 + x$ wird in $P_2$ als  vektor geschrieben:  $ a = \left( \begin{array}{c} 0 \\ 1 \\ 1 \end{array} \right) $
 
 Dann die Ableitung ist: A*a
 
$$   
\begin{pmatrix}
0 & 1 & 0 \\
0 & 0 & 2 \\
\end{pmatrix}
  \left( \begin{array}{c} 0 \\ 1 \\ 1 \end{array} \right) = \left( \begin{array}{c} 1 \\ 2 \end{array} \right) = 2x + 1 $$


In [4]:
A = np.matrix([[0,1,0],[0,0,2]])
a =  np.array((0,1,1)).T
np.dot(A, a)
A.dot(a)


matrix([[1, 2]])


###Aufgabe 4

Durch die Vorschrift $f(x) = Ax$ mit 
$$ A = 
\begin{pmatrix}
1 & 1 & 0 \\
2 & 1 & 1 \\
\end{pmatrix}
$$

ist eine lineare Abbildung von $\mathbb{R}^3$ nach $\mathbb{R}^2$ definiert(A stellt $f$ bezüglich der kanonischen
Basis dar). Bestimmen Sie Basen von $\mathbb{R}^3$ bzw. $\mathbb{R}^2$ , so dass man $f$ durch die Matrix

$$ B = 
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{pmatrix}
$$
darstellen kann bzgl. diesen Basen.

###Lösung

$ \underbrace{\mathbb{R}^3}_\text{kanonische Basen} \qquad  \xrightarrow{A}  \qquad   \underbrace{\mathbb{R}^2}_\text{kanonische Basen} $

$\quad \underbrace{\mathbb{R}^3}_\text{Basen} \qquad \qquad  \xrightarrow{B}  \qquad \qquad \underbrace{\mathbb{R}^2}_\text{Basen} $

Weil, es kanonische Basen sind: $$f(x) = A x$$


$$ f \left( \begin{array}{c} 1 \\ 0 \\ 0 \end{array} \right) = \left( \begin{array}{c} 1 \\ 2 \end{array} \right), \quad f \left( \begin{array}{c} 0 \\ 1 \\ 0 \end{array} \right) = \left( \begin{array}{c} 1 \\ 1 \end{array} \right), \quad f \left( \begin{array}{c} 0 \\ 0 \\ 1 \end{array} \right) = \left( \begin{array}{c} 0 \\ 1 \end{array} \right)$$




$f(e_1) =  \left( \begin{array}{c} 1 \\ 2 \end{array} \right) = b_{11} \left( \begin{array}{c} v_1 \end{array} \right) + b_{21} \left( \begin{array}{c} v_2 \end{array} \right)  \Longrightarrow  v_1 = \left( \begin{array}{c} 1 \\ 2 \end{array} \right)$
 
$f(e_2) = \left( \begin{array}{c} 1 \\ 1 \end{array} \right) = b_{12} \left( \begin{array}{c} v_1 \end{array} \right) + b_{22} \left( \begin{array}{c} v_2 \end{array} \right)  \Longrightarrow  v_2 = \left( \begin{array}{c} 1 \\ 1 \end{array} \right)$

$f(e_3) = \left( \begin{array}{c} 0 \\ 1 \end{array} \right) \neq b_{13} \left( \begin{array}{c} v_1 \end{array} \right) + b_{23} \left( \begin{array}{c} v_2 \end{array} \right) = \left( \begin{array}{c} 0 \\ 0 \end{array} \right)  \Longrightarrow  \mathbb{R}^3 = \{e_1,e_2,v \} $


Wir müssen die neue Basis finden: Idee $\Longrightarrow Av=0$ lösen und v als neue Basis für $\mathbb{R}^3$ addieren .

Die neue Basen sind:

$\mathbb{R}^3 = \left\{ \left( \begin{array}{c} 1 \\ 0 \\ 0 \end{array} \right),\left( \begin{array}{c} 0 \\ 1 \\ 0 \end{array} \right),\left( \begin{array}{r} -1 \\ 1 \\ 1 \end{array} \right) \right\} $

$\mathbb{R}^2 = \left\{ \left( \begin{array}{c} 1 \\ 2 \end{array} \right),\left( \begin{array}{c} 1 \\ 1 \end{array} \right) \right\} $



In [5]:

from numpy.linalg import svd

def nullspace(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = svd(A)
    tol = max(atol, rtol * s[0])
    nnz = (s >= tol).sum()
    ns = vh[nnz:].conj().T
    return ns
A = np.matrix([[1,1,0],[2,1,1]])
v = np.around(nullspace(A))
print(v)

[[-1.]
 [ 1.]
 [ 1.]]
